export const CHAT_USER = [
  {
    id: 1,
    name: 'Sanket Sahu',
    uri:
      'https://pbs.twimg.com/profile_images/1188747996843761665/8CiUdKZW_400x400.jpg',
    lastMessage: 'Please give your feedback',
    messageColor: 'black',
    status: 'online',
    time: '09:00 PM',
    unreadMessage: '2',
    showIcon: false,
    iconName: 'checkmark',
    iconType: 'Ionicons',
    iconColor: 'black',
  },
  {
    id: 2,
    name: 'Gaurav Guha',
    uri:
      'https://pbs.twimg.com/profile_images/1177303899243343872/B0sUJIH0_400x400.jpg',
    lastMessage: 'Call back us',
    messageColor: 'black',
    status: 'offline',
    time: '09:00 PM',
    unreadMessage: '1',
    showIcon: false,
    iconName: 'checkmark',
    iconType: 'Ionicons',
    iconColor: 'black',
  },
  {
    id: 3,
    name: 'Rohit Singh',
    uri:
      'https://pbs.twimg.com/profile_images/1260766060401188864/ySJfMIbZ_400x400.jpg',
    lastMessage: 'Video game ruined my life',
    messageColor: 'black',
    status: 'offline',
    time: '10 Jun',
    unreadMessage: '0',
    showIcon: true,
    iconName: 'checkmark-done',
    iconType: 'Ionicons',
    iconColor: 'green.500',
  },
  {
    id: 4,
    name: 'Ankur Kedia',
    uri:
      'https://pbs.twimg.com/profile_images/1309797238651060226/18cm6VhQ_400x400.jpg',
    messageColor: 'black',
    lastMessage: 'Congratulations',
    status: 'online',
    time: 'yesterday',
    unreadMessage: '0',
    showIcon: true,
    iconName: 'checkmark',
    iconType: 'Ionicons',
    iconColor: 'black',
  },
  {
    id: 5,
    name: 'Suraj Ahmed',
    uri:
      'https://pbs.twimg.com/profile_images/983582580372004864/h9ccP0Ea_400x400.jpg',
    messageColor: 'red.500',
    lastMessage: 'Missed Call',
    status: 'online',
    time: '09:00 PM',
    unreadMessage: '2',
    showIcon: true,
    iconName: 'phone-missed',
    iconColor: 'red.500',
  },
];
